import 'bootstrap/dist/css/bootstrap.min.css';
import './global.css'
import PrincipalOffCanvas from './Components/PrincipalOffCanvas';
import Menu from './Components/Menu';
import ButtonPrincipalOffCanvas from './Components/ButtonPrincipallOffCanvas';

// ButtonPrincipalOffCanvas

export const metadata = {
  title: "Next App Example",
  description: "Generated by create next app",
  icons: {
    icon: '/smniling_cat.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="light" suppressHydrationWarning>
      <body>
        <PrincipalOffCanvas/>
        <Menu/>

        {children}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossOrigin="anonymous"></script>
        <script src="/toggleColors.js"></script>
      </body>
    </html>
  );
}
