export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/smniling_cat.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        layout1 layout1 layout1 layout1 layout1 layout1 
        {children}
      </body>
    </html>
  );
}
