name: Deploy in ECR
run-name: ${{ github.actor }} is uploading to ECR
on:
  push:
    branches: [main]
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::474414115297:role/github_connect_s3
        aws-region: us-east-1
    - name: Upload to S3
      run: |
        aws s3 cp ./acerca-de-mi s3://personal-presenation/acerca-de-mi/ --recursive

        aws s3 cp ./principal_index.html s3://personal-presenation/
        aws s3 cp ./style.css s3://personal-presenation/
        aws s3 cp ./vars.json s3://personal-presenation/

        aws s3 cp ./front_examples/vueFront/dist s3://personal-presenation/front_examples/vueFront/dist/ --recursive